### ISSUE TITLE
透明度叠加

### ISSUE THREAD

**Issue by zhictory** [zhictory/frontend#1]
如果两个盒子是父子关系且两个都有 opacity 值，则子盒的透明值是父子 opacity 值相乘，测试如下：

CSS：
```css
.outer-1 {
    width:  100px;
    height:  100px;
    background-color:  #fff;
}
.inner-1 {
    width:  100px;
    height:  100px;
    background-color:  #ffb6c1;
    opacity:  .25;
}
.outer-2 {
    width:  100px;
    height:  100px;
    background-color:  #fff;
    opacity:  .5;
}
.inner-2 {
    width:  100px;
    height:  100px;
    background-color:  #ffb6c1;
    opacity:  .5;
}
```

HTML：
```html
<div  class="outer-1">
    <div  class="inner-1">inner 的 opacity 是 .81，outer 的 opacity 是 1，相乘是 .81。背景颜色加透明后是 #ffc4cd。</div>
</div>
<div  class="outer-2">
    <div  class="inner-2">inner 的 opacity 是 .9，outer 的 opacity 是 .9，相乘是 .81。背景颜色加透明后是 #ffc4cd，与上面效果一样，证明结论是正确的。</div>
</div>
```

效果：
![image](https://user-images.githubusercontent.com/6872950/43041465-0c3e7520-8d94-11e8-9960-3f5b9ae4a04f.png)
