### ISSUE TITLE
内联元素间隙问题 2

### ISSUE THREAD

**Issue by zhictory** [zhictory/frontend#3]
内联元素两两之间为什么会有空隙呢？如图所示：

![image](https://user-images.githubusercontent.com/6872950/43041501-47731f32-8d95-11e8-93b7-1f6590d4eb6a.png)

其实空隙是空白节点，比如空格或换行符。

既然是空白字符引起，那么在 HTML 中不留空白字符即可去掉空隙：

```html
<body>
    <span>123</span>
    <span>123</span>
    <span>123</span>
    <!-- 修改为 -->
    <span>123</span><span>123</span><span>123</span>
</body>
```

如果不想修改 HTML，修改 CSS 也是可以的，给父元素设置字体为0，使得空白节点消失，并给子元素重新设置字体大小：

```css
body {
    font-size: 0;
}
span {
    font-size: 12px;
}
```
