### ISSUE TITLE
大图居中

### ISSUE THREAD

**Issue by zhictory** [zhictory/frontend#4]
一般要让图片居中的话，使用：

```css
.img-wrap {
    text-align: center;
}
```

但是如果图片比浏览器窗口宽时，此方法无法让图片居中，因为图片左边缘会贴住浏览器左边缘。

有两个方法可以解决：

1. 使用 background 的 center 值

    ```css
    .img-wrap {
        background: url(./img.jpg) center;
    }
    ```

1. 使用图片居中定位

    ```css
    img {
        position: relative;
        width: 200px;
        left: -100px;
        margin-left: 50%;
    }
    /* 或 */
    img {
        position: relative;
        width: 200px;
        left: transform: translateX(-50%);
        margin-left: 50%;
    }
    ```
    例子：[大图居中](https://codepen.io/zhictory/full/PBPZyz/)
    
    ![image](https://user-images.githubusercontent.com/6872950/43041513-b4e91ca6-8d95-11e8-80b5-a0efec20113a.png)

    
    这例子是利用图片中线，先把图片左边缘居中，再用 left 或 transform 把图片左移一半，这样来达到图片居中的效果。其中，transform 不需要知道图片宽度，而 left 需要知道。
