### ISSUE TITLE
CSS hack

### ISSUE THREAD

**Issue by zhictory** [zhictory/frontend#7]
CSS hack 就是针对不同的浏览器去写不同的 CSS 代码，让它能够在不同浏览器中实现相同效果。

使用 hack 的原因是不同浏览器（IE6 IE7 IE8 Firefox 等）对 CSS 解析的标准不同，从而可以用浏览器的兼容性差异来解决浏览器的兼容性问题。

> 现在很多 hacks 已经抛弃了最初的原则。滥用 hack 会导致浏览器更新之后产生更多的兼容性问题。**因此，并不推荐使用 CSS hack 来解决兼容性问题。**

CSS hack 遵循三条原则：

- 有效： 能够通过 Web 标准的验证
- 只针对太古老的/不再开发的/已被抛弃的浏览器， 而不是目前的主流浏览器
- 代码要丑陋。让人记住这是一个不得已而为之的 Hack, 时刻记住要想办法去掉它

CSS hack 的实现方式：

1. 利用浏览器对相同代码的解析和支持的不同实现的 hack
2. 以 Firefox 或 Webkit 特有的扩展样式实现的 hack
3. 利用 IE 对标准的支持缺陷写的 hack
4. 以 IE 特有的条件注释为基础的 hack

```css
*+selector {
    /* IE7 */
}
*selector {
    /* IE6 */
}
selector {
    _property: value; /* IE6 */
    -property: value; /* IE6 */
    *property: value; /* IE6、IE7 */
    property: value\9; /* IE6、IE7、IE8 */
}
```

参考：
> [RY8003: 各浏览器对 CSS 错误解析规则的差异及 CSS hack](http://w3help.org/zh-cn/causes/RY8003)
